import type { DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, Module, PartialLangiumServices } from 'langium';
import { createDefaultModule, createDefaultSharedModule, inject } from 'langium';
import { LangBiTeAugmentationDSLGeneratedModule, LangBiTeAugmentationDSLGeneratedSharedModule } from './generated/module.js';
import { AugmenterValidator, registerValidationChecks } from './langbite-augmentation-dsl-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type AugmenterAddedServices = {
    validation: {
        AugmenterValidator: AugmenterValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type AugmenterServices = LangiumServices & AugmenterAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const AugmenterModule: Module<AugmenterServices, PartialLangiumServices & AugmenterAddedServices> = {
    validation: {
        AugmenterValidator: () => new AugmenterValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createAugmenterServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Augmenter: AugmenterServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        LangBiTeAugmentationDSLGeneratedSharedModule
    );
    const Augmenter = inject(
        createDefaultModule({ shared }),
        LangBiTeAugmentationDSLGeneratedModule,
        AugmenterModule
    );
    shared.ServiceRegistry.register(Augmenter);
    registerValidationChecks(Augmenter);
    return { shared, Augmenter };
}
